[ids]
*
-004c:2027

[main]
# Turns physical Caps Lock into your left Windows/Super key
capslock = leftmeta

# Turns your physical Start button into the 'Menu' key
leftmeta = menu

[alt]
space = enter

